USE master

--ALTER DATABASE [UniversityDB] SET OFFLINE WITH ROLLBACK IMMEDIATE 
--ALTER DATABASE [UniversityDB] SET ONLINE﻿
GO

ALTER DATABASE [UniversityDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE [UniversityDB] SET MULTI_USER WITH ROLLBACK IMMEDIATE

GO

IF EXISTS(SELECT * FROM sys.databases WHERE name='UniversityDB')
DROP DATABASE [UniversityDB]

CREATE DATABASE [UniversityDB]


