USE master

--ALTER DATABASE [UniversityDB] SET OFFLINE WITH ROLLBACK IMMEDIATE 
--ALTER DATABASE [UniversityDB] SET ONLINE﻿
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name='UniversityDB')
BEGIN
ALTER DATABASE [UniversityDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE [UniversityDB] SET MULTI_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [UniversityDB]
END

GO

CREATE DATABASE [UniversityDB]


