//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseGeneration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataBaseGeneration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master
        ///
        ///--ALTER DATABASE [UniversityDB] SET OFFLINE WITH ROLLBACK IMMEDIATE 
        ///--ALTER DATABASE [UniversityDB] SET ONLINE﻿
        ///GO
        ///
        ///ALTER DATABASE [UniversityDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
        ///ALTER DATABASE [UniversityDB] SET MULTI_USER WITH ROLLBACK IMMEDIATE
        ///
        ///GO
        ///
        ///IF EXISTS(SELECT * FROM sys.databases WHERE name=&apos;UniversityDB&apos;)
        ///DROP DATABASE [UniversityDB]
        ///
        ///CREATE DATABASE [UniversityDB]
        ///
        ///
        ///.
        /// </summary>
        internal static string preparescript {
            get {
                return ResourceManager.GetString("preparescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [UniversityDB]
        ///GO
        ////****** Object:  Table [dbo].[StudyRange]    Script Date: 11/24/2013 03:45:51 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[StudyRange](
        ///	[ID] [int] IDENTITY(1,1) NOT NULL,
        ///	[Year] [int] NOT NULL,
        ///	[Part] [int] NOT NULL,
        /// CONSTRAINT [PK_StudyRange] PRIMARY KEY CLUSTERED 
        ///(
        ///	[ID] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ////* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema {
            get {
                return ResourceManager.GetString("schema", resourceCulture);
            }
        }
    }
}
